apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app
  namespace: eks-app
  labels:
    app: eks-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      serviceAccountName: eks-app-sa
      containers:
        - name: eks-app
          image: 688372068827.dkr.ecr.eu-west-2.amazonaws.com/eks-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
