apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-app-sa
  namespace: eks-app
---
apiVersion: v1
kind: Service
metadata:
  name: eks-app
  namespace: eks-app
spec:
  selector:
    app: eks-app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
